spring.application.name=course-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/cms_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=020106
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Chỉ định cho Springdoc biết nơi chứa các RestController
springdoc.packages-to-scan=com.cms.controller
springdoc.paths-to-match=/api/**
# ===============================================
# Cấu hình JWT (Đúng tên biến)
# ===============================================
app.jwt-secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt-expiration-milliseconds=86400000